path: D:/Projects/OCR-answer-sheet/data

train: D:/Projects/OCR-answer-sheet/data/train

val: D:/Projects/OCR-answer-sheet/data/validation

names:
  0: sheet
  1: question_box
  2: exam_id
  3: student_id